name: padshare
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rave_flutter:
      path: ../rave_flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  country_code_picker: ^2.0.2
  flutter_svg: ^0.19.0
#  firebase_core: ^1.0.2
#  firebase_auth: ^1.0.1
    #firebase_auth: ^0.19.0+1
  cloud_firestore: ^1.0.7
  sms_autofill: ^2.2.0
  image_picker: ^0.8.4+5
  image_cropper: ^1.3.1
  firebase_storage: ^10.2.6
  auto_size_text_field: ^1.0.1
  progress_indicators: ^1.0.0
  flutter_secure_storage: ^5.0.2
  json_annotation: ^4.0.1
  flutter_native_image: ^0.0.6
  uuid: ^3.0.4
  place_picker: ^0.9.18
  google_sign_in: ^5.0.2
  sqflite: ^2.0.0+3
  path: ^1.8.0
  #search_widget: ^1.0.2
  get: ^4.1.4
  badges: ^2.0.1
  jiffy: ^5.0.0
  fl_chart: ^0.12.3
  flutter_switch: ^0.3.2
#  firebase_messaging: ^10.0.1
  flutter_local_notifications: ^8.2.0
  flutter_speed_dial: ^5.0.0+1
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  timezone: ^0.8.0
  timeago: ^3.2.2
  firebase_core: ^1.12.0
  #cloud_firestore: ^2.3.0 #^3.1.9
  firebase_auth: ^3.3.8
  firebase_messaging: ^11.2.7
#  fluttertoast: ^8.0.8
    #cloud_functions: ^1.0.3
    #flutterwave: 0.0.3-dev.2
    #rave_flutter: ^0.0.9-alpha+2
    #permission_handler: ^6.1.1

dependency_overrides:
#  firebase_messaging_platform_interface: 3.2.2
  firebase_messaging_platform_interface: 3.1.0
  firebase_auth_platform_interface: 6.1.4

dev_dependencies:
  build_runner:
  json_serializable: ^4.0.2
  intl: ^0.17.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/images/screen1.png
    - assets/images/screen2.png
    - assets/images/logo.png
    - assets/images/person.svg
    - assets/images/email.svg
    - assets/images/DateOf_birth.svg
    - assets/images/home.svg
    - assets/images/userProfile.svg
    - assets/images/profile.png
    - assets/images/earth-globe-with-continents-maps.png
    - assets/images/IMG-20210527-WA0009.jpg
    - assets/images/proIcon.svg
    - assets/images/padsicon.png
    - assets/images/addStory.png
    - assets/images/card.png
    - assets/images/imagecard.png
    - assets/images/cardicon2.png
    - assets/images/imagepic.png
    - assets/images/heart.svg
    - assets/images/heart.png
    - assets/images/credit-card.png
    - assets/images/message.svg
    - assets/images/share.svg
    - assets/images/Editicon.png
    - assets/images/profileuser.png
    - assets/images/camera.svg
    - assets/images/picture.svg
    - assets/images/send.svg
    - assets/images/impact.png
    - assets/images/shop.png
    - assets/images/profile1.png
    - assets/images/home.png
    - assets/images/notification.svg
    - assets/images/edit.svg
    - assets/images/girls.png
    - assets/images/tick.png
    - assets/images/thumbs.svg
    - assets/images/padshared_logo.png
    - assets/images/graph.png
    - assets/images/activelist.png
    - assets/images/plusSign.png
    - assets/images/user1.png
    - assets/images/user2.png
    - assets/images/bell.png
    - assets/images/message-icon.png
    - assets/images/user3.png
    - assets/images/plusIcon.png
    - assets/images/giveIcon.png
    - assets/images/DonationFailed.png
    - assets/images/dark-placeholder.png
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/addCat.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.png
    - assets/ca/lets-encrypt-r3.pem
    - assets/images/cloud-computing.png
    - assets/images/signal.png
    - assets/images/h.png
    - assets/images/management.png
    - assets/images/PADSHARE-LOGO.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Gothanm
      fonts:
        - asset: fonts/Gotham-Bold.otf
        - asset: fonts/GothamLight.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
